# Generated by Django 3.2 on 2021-04-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_note_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
    ]
